const bdInitialEleves = [
    {
        "id": 1,
        "prenom": "Mouna",
        "nom": "aarour",
        "email": "aarour@gmail.com",
        "img": null
    }, {
        "id": 2,
        "prenom": "Salah Eddine",
        "nom": "aboulkacim",
        "email": "aboulkacim@gmail.com",
        "img": null
    }, {
        "id": 3,
        "prenom": "Jarod",
        "nom": "acloque",
        "email": "acloque@gmail.com",
        "img": null
    }, {
        "id": 4,
        "prenom": "Abdellah",
        "nom": "adansar",
        "email": "adansar@gmail.com",
        "img": null
    }, {
        "id": 5,
        "prenom": "Florian",
        "nom": "aime",
        "email": "aime@gmail.com",
        "img": null
    }, {
        "id": 6,
        "prenom": "Youssef",
        "nom": "ansari",
        "email": "ansari@gmail.com",
        "img": null
    }, {
        "id": 7,
        "prenom": "Syrine",
        "nom": "atoui",
        "email": "atoui@gmail.com",
        "img": null
    }, {
        "id": 8,
        "prenom": "Anas",
        "nom": "balrhi",
        "email": "balrhi@gmail.com",
        "img": null
    }, {
        "id": 9,
        "prenom": "Cecile",
        "nom": "barouk",
        "email": "barouk@gmail.com",
        "img": null
    }, {
        "id": 10,
        "prenom": "Florian",
        "nom": "barrali",
        "email": "barrali@gmail.com",
        "img": null
    }, {
        "id": 11,
        "prenom": "Guillaume",
        "nom": "benezech--loustalot-forest",
        "email": "benezech@gmail.com",
        "img": null
    }, {
        "id": 12,
        "prenom": "Gautier",
        "nom": "benoit",
        "email": "benoit@gmail.com",
        "img": null
    }, {
        "id": 13,
        "prenom": "Lena",
        "nom": "bitch",
        "email": "bitch@gmail.com",
        "img": null
    }, {
        "id": 14,
        "prenom": "Allaye",
        "nom": "bocoum",
        "email": "bocoum@gmail.com",
        "img": null
    }, {
        "id": 15,
        "prenom": "Rania",
        "nom": "bordjiba",
        "email": "bordjiba@gmail.com",
        "img": null
    }, {
        "id": 16,
        "prenom": "Theo",
        "nom": "borreani",
        "email": "borreani@gmail.com",
        "img": null
    }, {
        "id": 17,
        "prenom": "Maxence",
        "nom": "bourgeat",
        "email": "bourgeat@gmail.com",
        "img": null
    }, {
        "id": 18,
        "prenom": "Ibrahim",
        "nom": "bouyghf",
        "email": "bouyghf@gmail.com",
        "img": null
    }, {
        "id": 19,
        "prenom": "Julien",
        "nom": "brandi",
        "email": "brandi@gmail.com",
        "img": null
    }, {
        "id": 20,
        "prenom": "Jeremie",
        "nom": "brezzo",
        "email": "brezzo@gmail.com",
        "img": null
    }, {
        "id": 21,
        "prenom": "Julien",
        "nom": "brunetti",
        "email": "brunetti@gmail.com",
        "img": null
    }, {
        "id": 22,
        "prenom": "Thibault",
        "nom": "canavaggio",
        "email": "canavaggio@gmail.com",
        "img": null
    }, {
        "id": 23,
        "prenom": "Thomas",
        "nom": "choubrac",
        "email": "choubrac@gmail.com",
        "img": null
    }, {
        "id": 24,
        "prenom": "Clement",
        "nom": "colin",
        "email": "colin@gmail.com",
        "img": null
    }, {
        "id": 25,
        "prenom": "Tuan Linh",
        "nom": "dao",
        "email": "dao@gmail.com",
        "img": null
    }, {
        "id": 26,
        "prenom": "Mahussi",
        "nom": "datongnon",
        "email": "datongnon@gmail.com",
        "img": null
    }, {
        "id": 27,
        "prenom": "Arthur",
        "nom": "dauphin",
        "email": "dauphin@gmail.com",
        "img": null
    }, {
        "id": 28,
        "prenom": "Mouhamed Gando",
        "nom": "diallo",
        "email": "diallo@gmail.com",
        "img": null
    }, {
        "id": 29,
        "prenom": "Serigne Rawane",
        "nom": "diop",
        "email": "diop@gmail.com",
        "img": null
    }, {
        "id": 30,
        "prenom": "Zouhair",
        "nom": "dkhissi",
        "email": "dkhissi@gmail.com",
        "img": null
    }, {
        "id": 31,
        "prenom": "Ayoub",
        "nom": "el alami el filali",
        "email": "alami@gmail.com",
        "img": null
    }, {
        "id": 32,
        "prenom": "Sawsen",
        "nom": "el bahri",
        "email": "bahri@gmail.com",
        "img": null
    }, {
        "id": 33,
        "prenom": "Lyne",
        "nom": "el dada",
        "email": "dada@gmail.com",
        "img": null
    }, {
        "id": 34,
        "prenom": "Patrick",
        "nom": "fernandes de faria",
        "email": "fernandes@gmail.com",
        "img": null
    }, {
        "id": 35,
        "prenom": "Evan",
        "nom": "gallice",
        "email": "gallice@gmail.com",
        "img": null
    }, {
        "id": 36,
        "prenom": "Mohamed",
        "nom": "ghoul",
        "email": "ghoul@gmail.com",
        "img": null
    }, {
        "id": 37,
        "prenom": "Valentin",
        "nom": "gomy",
        "email": "gomy@gmail.com",
        "img": null
    }, {
        "id": 38,
        "prenom": "Ismail",
        "nom": "hamaimou",
        "email": "hamaimou@gmail.com",
        "img": null
    }, {
        "id": 39,
        "prenom": "Destiny",
        "nom": "hanna",
        "email": "hanna@gmail.com",
        "img": null
    }, {
        "id": 40,
        "prenom": "Zakaria",
        "nom": "hassad",
        "email": "hassad@gmail.com",
        "img": null
    }, {
        "id": 41,
        "prenom": "Zaid",
        "nom": "laasri",
        "email": "laasri@gmail.com",
        "img": null
    }, {
        "id": 42,
        "prenom": "Dylan",
        "nom": "lafaire",
        "email": "lafaire@gmail.com",
        "img": null
    }, {
        "id": 43,
        "prenom": "Andrea",
        "nom": "larboullet--marin",
        "email": "larboullet@gmail.com",
        "img": null
    }, {
        "id": 44,
        "prenom": "Killian",
        "nom": "le borgne",
        "email": "borgne@gmail.com",
        "img": null
    }, {
        "id": 45,
        "prenom": "Bastien",
        "nom": "lefumeux",
        "email": "lefumeux@gmail.com",
        "img": null
    }, {
        "id": 46,
        "prenom": "Morgane",
        "nom": "lessatini",
        "email": "lessatini@gmail.com",
        "img": null
    }, {
        "id": 47,
        "prenom": "Clement",
        "nom": "loze",
        "email": "loze@gmail.com",
        "img": null
    }, {
        "id": 48,
        "prenom": "Neila",
        "nom": "mansouri",
        "email": "mansouri@gmail.com",
        "img": null
    }, {
        "id": 49,
        "prenom": "Gautier",
        "nom": "martin",
        "email": "martin@gmail.com",
        "img": null
    }, {
        "id": 50,
        "prenom": "Ralph",
        "nom": "mohdad",
        "email": "mohdad@gmail.com",
        "img": null
    }, {
        "id": 51,
        "prenom": "Amina",
        "nom": "mouchtahi",
        "email": "mouchtahi@gmail.com",
        "img": null
    }, {
        "id": 52,
        "prenom": "Kenneth",
        "nom": "padonou loko",
        "email": "padonou@gmail.com",
        "img": null
    }, {
        "id": 53,
        "prenom": "Quentin",
        "nom": "pierson",
        "email": "piersonQt@gmail.com",
        "img": null
    }, {
        "id": 54,
        "prenom": "Thomas",
        "nom": "pierson",
        "email": "piersonTh@gmail.com",
        "img": null
    }, {
        "id": 55,
        "prenom": "Noemie",
        "nom": "poujol",
        "email": "poujol@gmail.com",
        "img": null
    }, {
        "id": 56,
        "prenom": "Arthur",
        "nom": "prudent",
        "email": "prudent@gmail.com",
        "img": null
    }, {
        "id": 57,
        "prenom": "Florian",
        "nom": "pustel",
        "email": "pustel@gmail.com",
        "img": null
    }, {
        "id": 58,
        "prenom": "Nicolas",
        "nom": "quatela",
        "email": "quatela@gmail.com",
        "img": null
    }, {
        "id": 59,
        "prenom": "Adam",
        "nom": "reguig",
        "email": "reguig@gmail.com",
        "img": null
    }, {
        "id": 60,
        "prenom": "Theo",
        "nom": "ripoll",
        "email": "ripoll@gmail.com",
        "img": null
    }, {
        "id": 61,
        "prenom": "Leo",
        "nom": "robin",
        "email": "robin@gmail.com",
        "img": null
    }, {
        "id": 62,
        "prenom": "Enzo",
        "nom": "rocamora",
        "email": "rocamora@gmail.com",
        "img": null
    }, {
        "id": 63,
        "prenom": "Nicolas",
        "nom": "saillant",
        "email": "saillant@gmail.com",
        "img": null
    }, {
        "id": 64,
        "prenom": "Jonathan",
        "nom": "samuel",
        "email": "samuel@gmail.com",
        "img": null
    }, {
        "id": 65,
        "prenom": "Pierre",
        "nom": "save",
        "email": "save@gmail.com",
        "img": null
    }, {
        "id": 66,
        "prenom": "Melissa",
        "nom": "silva fernandes",
        "email": "silva@gmail.com",
        "img": null
    }, {
        "id": 67,
        "prenom": "Theo",
        "nom": "stringat",
        "email": "stringat@gmail.com",
        "img": null
    }, {
        "id": 68,
        "prenom": "Irina",
        "nom": "sukhorukova",
        "email": "sukhorukova@gmail.com",
        "img": null
    }, {
        "id": 69,
        "prenom": "Siham",
        "nom": "tabbaa",
        "email": "tabbaa@gmail.com",
        "img": null
    }, {
        "id": 70,
        "prenom": "Marouane",
        "nom": "taki edine",
        "email": "taki@gmail.com",
        "img": null
    }, {
        "id": 71,
        "prenom": "Thi Thanh Thuy",
        "nom": "trinh",
        "email": "trinh@gmail.com",
        "img": null
    }, {
        "id": 72,
        "prenom": "Alessandro",
        "nom": "vartanian",
        "email": "vartanian@gmail.com",
        "img": null
    }, {
        "id": 73,
        "prenom": "Mattheo",
        "nom": "vasseur",
        "email": "vasseur@gmail.com",
        "img": null
    }, {
        "id": 74,
        "prenom": "Axel",
        "nom": "verkimpe",
        "email": "verkimpe@gmail.com",
        "img": null
    }, {
        "id": 75,
        "prenom": "Ilan",
        "nom": "wanounou",
        "email": "wanounou@gmail.com",
        "img": null
    }, {
        "id": 76,
        "prenom": "Zeinab",
        "nom": "wazne",
        "email": "wazne@gmail.com",
        "img": null
    }, {
        "id": 77,
        "prenom": "Hicham",
        "nom": "zaher",
        "email": "zaher@gmail.com",
        "img": null
    }]

export { bdInitialEleves };